# AWS-specific overrides for your existing codebase
global:
  cloud: aws
  environment: production

# Backend environment overrides for AWS
backend:
  env:
    # Database URL format that matches your settings.py
    DATABASE_URL: "postgresql+asyncpg://xfinity_admin:${DB_PASSWORD}@xfinity-ai-postgres-production.cluster-xyz.us-west-2.rds.amazonaws.com:5432/xfinity_ai"

    # Redis URL format that matches your settings.py
    REDIS_URL: "redis://xfinity-ai-redis-production.xyz.cache.amazonaws.com:6379/0"

    # CORS origins for AWS ALB
    CORS_ORIGINS: "https://app.xfinity-ai.com,https://admin.xfinity-ai.com"

# Ingress configuration for AWS ALB (matches your existing setup)
ingress:
  enabled: true
  className: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: ${AWS_CERTIFICATE_ARN}
    alb.ingress.kubernetes.io/ssl-redirect: "443"
  hosts:
    - host: api.xfinity-ai.com
      paths:
        - path: /
          pathType: Prefix
          service: backend-service
          port: 8000
    - host: app.xfinity-ai.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend-service
          port: 80

# AWS-specific monitoring
monitoring:
  enabled: true
  cloudwatch:
    enabled: true
    logGroup: "/aws/eks/xfinity-ai"

  # Use your existing Prometheus config
  prometheus:
    enabled: true
    storageClass: gp3
    retention: "15d"

# Storage classes for AWS
storage:
  backend:
    storageClass: gp3
  database:
    storageClass: gp3
    size: 100Gi
