# Azure-specific values for Xfinity AI Platform
global:
  cloud: azure
  environment: production

# Azure-specific ingress configuration
ingress:
  enabled: true
  className: "azure-application-gateway"
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/request-timeout: "30"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
  hosts:
    - host: app.xfinity-ai.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: xfinity-ai-frontend
            port: 3000
        - path: /api
          pathType: Prefix
          service:
            name: xfinity-ai-backend
            port: 8000
  tls:
    - secretName: xfinity-ai-tls
      hosts:
        - app.xfinity-ai.com

# Azure-specific image configuration
image:
  backend:
    repository: xfinityaiacr.azurecr.io/xfinity-ai/backend
    tag: latest
    pullPolicy: Always
  frontend:
    repository: xfinityaiacr.azurecr.io/xfinity-ai/frontend
    tag: latest
    pullPolicy: Always

# Azure-specific storage configuration
persistence:
  storageClass: "managed-premium"
  accessMode: ReadWriteOnce
  size: 10Gi

# Azure-specific database configuration
database:
  type: azure-postgresql
  host: xfinity-ai-postgres.postgres.database.azure.com
  port: 5432
  ssl: require

# Azure-specific Redis configuration
redis:
  type: azure-cache
  host: xfinity-ai-redis.redis.cache.windows.net
  port: 6380
  ssl: true

# Azure-specific monitoring
monitoring:
  enabled: true
  provider: azure-monitor
  applicationInsights:
    enabled: true
    instrumentationKey: ""

# Azure-specific resource limits
resources:
  backend:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  frontend:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Azure-specific autoscaling
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
