groups:
  - name: backend-alerts
    rules:
      - alert: HighRequestLatency
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job="backend"}[5m])) by (le)) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High request latency on backend (>2s p95)"

      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{job="backend",status=~"5.."}[5m])) by (job) / sum(rate(http_requests_total{job="backend"}[5m])) by (job) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate on backend (>5%)"

  - name: postgres-alerts
    rules:
      - alert: PostgresDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Postgres exporter is down"
