groups:
  - name: backend-alerts
    rules:
      - alert: HighAPIResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="xfinity-backend"}[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High API response time detected"
          description: "95th percentile response time is {{ $value }}s for {{ $labels.method }} {{ $labels.endpoint }}"

      - alert: WebSocketConnectionFailures
        expr: rate(websocket_connections_failed_total{job="xfinity-backend"}[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "WebSocket connection failures"
          description: "WebSocket connection failure rate is {{ $value }} per second"

      - alert: AIAgentFailures
        expr: rate(ai_agent_responses_failed_total{job="xfinity-backend"}[5m]) > 0.05
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "AI agent response failures"
          description: "AI agent {{ $labels.agent_type }} failing at {{ $value }} per second"

      - alert: KnowledgeBaseSearchFailures
        expr: rate(knowledge_base_search_failed_total{job="xfinity-backend"}[5m]) > 0.02
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "Knowledge base search failures"
          description: "Knowledge base search failure rate is {{ $value }} per second"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for endpoint {{ $labels.endpoint }}"
