global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8000"]
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
