version: '3.8'
services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: customer_support
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - monitoring
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:password@postgres:5432/customer_support?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    networks:
      - monitoring
  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring
  backend:
    build: ../backend
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATABASE_URL: postgresql+asyncpg://postgres:password@postgres:5432/customer_support
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - monitoring
  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../monitoring/prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - ../monitoring/grafana/:/var/lib/grafana
    networks:
      - monitoring
volumes:
  pgdata:

networks:
  monitoring:
    driver: bridge 