services:
  mlflow:
    image: python:3.11-slim
    container_name: xfinity-ai-mlflow
    working_dir: /mlflow
    command: >
      bash -c "
      pip install mlflow[extras]==2.11.1 psycopg2-binary &&
      mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri postgresql://user:password@db:5432/mlflow --default-artifact-root s3://mlflow-artifacts --serve-artifacts
      "
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - db
    networks:
      - xfinity-ai-network
    restart: unless-stopped

  jupyter:
    image: jupyter/tensorflow-notebook:latest
    container_name: xfinity-ai-jupyter
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=xfinity-ai-token
    volumes:
      - ../notebooks:/home/jovyan/work
      - jupyter_data:/home/jovyan
    networks:
      - xfinity-ai-network
    restart: unless-stopped

networks:
  xfinity-ai-network:
    external: true

volumes:
  jupyter_data: