apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: xfinity-ai
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "xfinity_ai"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  PROMETHEUS_METRICS_PORT: "8001"
  CORS_ORIGINS: "https://app.xfinity-ai.com"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: xfinity-ai
data:
  REACT_APP_API_URL: "https://api.xfinity-ai.com"
  REACT_APP_WS_URL: "wss://api.xfinity-ai.com"
  REACT_APP_ENV: "production"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: xfinity-ai
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - "alert_rules.yml"

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093

    scrape_configs:
      - job_name: 'xfinity-ai-backend'
        static_configs:
          - targets: ['backend-service:8001']
        metrics_path: '/metrics'
        scrape_interval: 30s
      
      - job_name: 'postgres-exporter'
        static_configs:
          - targets: ['postgres-exporter:9187']
      
      - job_name: 'redis-exporter'
        static_configs:
          - targets: ['redis-exporter:9121']
      
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            target_label: __meta_kubernetes_service_name
            regex: node-exporter
